# Generated by Django 4.2.8 on 2024-01-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstroClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('birth_date', models.CharField(max_length=100)),
                ('birth_time', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=100)),
                ('birth_state', models.CharField(max_length=100)),
                ('birth_country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('payment_amount', models.CharField(blank=True, max_length=100)),
                ('payment_signature', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
